#!/bin/bash

echo "Criação de diretórios"
mkdir publico adm ven sec

echo "======================"
echo "Criação de grupos de Usuarios"
groupadd GRP_ADM
groupadd GRP_VEN
groupadd GRP_SEC
echo "======================"

echo "Criação de usuarios ADM"
useradd carlos -c "carlos" -m -s /bin/bash
useradd mario -c "mario" -m -s /bin/bash 
useradd arnaldo -c "arnaldo" -m -s /bin/bash 

echo "Criação de usuarios VEN"
useradd pedro -c "pedro" -m -s /bin/bash 
useradd pati -c "pati" -m -s /bin/bash 
useradd paulo -c "paulo" -m -s /bin/bash 

echo "Criação de usuarios SEC"
useradd isla -c "isla" -m -s /bin/bash 
useradd tulio -c "tulio" -m -s /bin/bash 
useradd ayla -c "ayla" -m -s /bin/bash 

echo "======================"
echo "Adicionando ao grupo"
usermod -G GRP_ADM carlos
usermod -G GRP_ADM mario
usermod -G GRP_ADM arnaldo

usermod -G GRP_VEN pedro
usermod -G GRP_VEN pati
usermod -G GRP_VEN paulo

usermod -G GRP_VEN isla
usermod -G GRP_VEN tulio
usermod -G GRP_VEN ayla
echo "======================"

echo "======================"
echo "Permissões dos diretórios"
chown root:GRP_ADM /adm
chown root:GRP_VEN /ven
chown root:GRP_SEC /sec

chmod 770 /adm
chmod 770 /sec
chmod 770 /ven
chmod 777 /publica
echo "======================"

echo "Finalizado"
echo "======================"
